apiVersion: apps/v1
kind: Deployment
metadata:
  name: tax-calculator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tax-calculator
  template:
    metadata:
      labels:
        app: tax-calculator
    spec:
      containers:
      - name: tax-calculator
        image: us.icr.io/my-namespace-unique/tax-calculator:latest
        ports:
        - containerPort: 8080
