apiVersion: v1
kind: Service
metadata:
  name: tax-calculator-service
spec:
  selector:
    app: tax-calculator
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
